apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: expense
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployement.replicas }}
  selector:
    matchLabels:
      tier: frontend
      app: nginx
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
      # called as placeholder
        image: nginx:{{ .Values.deployment.imageVersion }}