kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: expense
spec:
  type: {{ .Values.service.type }}
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
  - name: nginx-svc-port  #svc==service
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80 # container port